default:
  # customer info
  customer.name: 客户名称
  ## project identifiers for the customer, used to extract data
  customer.projectid: 0
  # report configurations
  report.title:
    default: 大脑学习能力测评
  report.subtitle:
    default: 集体报告
  # use Android Sans font, more info at
  # https://www.freechinesefont.com/simplified-traditional-droid-sans-fallback/
  text.family: SimHei
  score.level:
    breaks: !expr qnorm(c(0, seq(0.05, 0.95, by = 0.1), 1)) * 15 + 100
    labels: !expr c("D", "C-", "C", "C+", "B-", "B", "B+", "A-", "A", "A+", "S")
  database:
    host: rdsr46zx53ze0ebceo1n.mysql.rds.aliyuncs.com
    user: readonly
    password: AZYonlyread2018

daxing:
  customer.name: 北京市大兴区
  customer.projectid: 263
  report.ability:
    code: [bci, Att, Mem, SC, Rsn, RT]
    name:
    - 大脑学习能力
    - 注意力
    - 记忆力
    - 自控力
    - 思维力
    - 反应力
    hlevel: [2, 3, 3, 3, 3, 3]
    hstyle: ""
    def:
    - 基础学习能力反映了注意力、记忆力、自控力、反应力和思维力这五个方面的综合水平，分数越高代表基础学习能力的综合发展水平越高。
    - 注意力是大脑接收和处理个体外部和内部信息的前提，只有被注意到的信息才能得到有有效的分析和处理才能用来解决问题并形成持久的记忆。注意力包含选择注意、持续注意和分配注意三个能力维度，本次施测下每个维度都有对应的施测题目，学生分数越高，代表注意力越集中。
    - 记忆力是人脑智力的集中体现，也是人脑比电脑更聪明的重要原因。个体的生存和发展需要不断掌握新的知识，记忆力能将这些 知识经验存储下来并合理运用。记忆连接着人的过去和未来，丰富着我们的精神生活并塑造着我们的性格。人脑包含复杂的记忆系统，其中联系记忆、语义记忆和短时记忆是三个重要的维度，每个维度都有对应的施测题目，学生分数越高，代表记忆力越好。
    - 自控力是人们能够根据目标和环境的要求，控制和改变自己的思想和行为，克服冲动并抵制诱惑，让自己的行为符合社会期许和长期目标的能力。自控力主要体现在控制冲动、抵制诱惑以及信息更新这三个维度，每个维度都有对应的施测题目，学生分数越高，代表自控力越强。
    - 思维力是人们接收到信息后，对信息进行归纳、概括及推理的过程。生活中，我们往往不满足于耳朵所听到的、眼睛所看到的，而是要找出事物之间的内在联系和规律，解决问题并创造出新的知识。思维力可以分为思维的灵活性、深刻性和独创性这三个维度，每个维度都有对应的施测题目，学生分数越高，代表思维力越强。
    - 反应力是对各种信息、要求和指令等做出快速反应的能力。速度是衡量反应力最重要的指标，它体现了大脑各个系统的协调、整合发展的水平，与整个神经网络的效率有密切关系。反应力可以从反应速度、言语速度和思维速度三个维度来测量。本次施测下每个维度都有对应的施测题目，学生分数越高，代表反应力越强。

lishui:
  customer.name: 广东省佛山市南海区里水镇
  customer.projectid: [415, 416]
  report.title:
    default: 大脑学习能力测评
  report.subtitle:
    default: 集体报告
    school: 学校集体报告
  report.ability:
    code: [bci, Att, Mem, SC, Rsn, RT]
    name:
    - 大脑学习能力
    - 注意力
    - 记忆力
    - 自控力
    - 思维力
    - 反应力
    hlevel: [2, 3, 3, 3, 3, 3]
    hstyle: ""
    def:
    - 大脑学习能力反映了注意力、记忆力、自控力、反应力和思维力这五个方面的综合水平，分数越高代表基础学习能力的综合发展水平越高。
    - 注意力是大脑接收和处理个体外部和内部信息的前提，只有被注意到的信息才能得到有有效的分析和处理才能用来解决问题并形成持久的记忆。注意力包含选择注意、持续注意和分配注意三个能力维度，本次施测下每个维度都有对应的施测题目，学生分数越高，代表注意力越集中。
    - 记忆力是人脑智力的集中体现，也是人脑比电脑更聪明的重要原因。个体的生存和发展需要不断掌握新的知识，记忆力能将这些 知识经验存储下来并合理运用。记忆连接着人的过去和未来，丰富着我们的精神生活并塑造着我们的性格。人脑包含复杂的记忆系统，其中联系记忆、语义记忆和短时记忆是三个重要的维度，每个维度都有对应的施测题目，学生分数越高，代表记忆力越好。
    - 自控力是人们能够根据目标和环境的要求，控制和改变自己的思想和行为，克服冲动并抵制诱惑，让自己的行为符合社会期许和长期目标的能力。自控力主要体现在控制冲动、抵制诱惑以及信息更新这三个维度，每个维度都有对应的施测题目，学生分数越高，代表自控力越强。
    - 思维力是人们接收到信息后，对信息进行归纳、概括及推理的过程。生活中，我们往往不满足于耳朵所听到的、眼睛所看到的，而是要找出事物之间的内在联系和规律，解决问题并创造出新的知识。思维力可以分为思维的灵活性、深刻性和独创性这三个维度，每个维度都有对应的施测题目，学生分数越高，代表思维力越强。
    - 反应力是对各种信息、要求和指令等做出快速反应的能力。速度是衡量反应力最重要的指标，它体现了大脑各个系统的协调、整合发展的水平，与整个神经网络的效率有密切关系。反应力可以从反应速度、言语速度和思维速度三个维度来测量。本次施测下每个维度都有对应的施测题目，学生分数越高，代表反应力越强。

erxiao:
  customer.name: 北京市第二实验小学
  report.ability:
    code:
    - blai
    - attention
    - memory
    - control
    - thinking
    - reaction
    - math
    name:
    - 基础学习能力
    - 注意力
    - 记忆力
    - 自控力
    - 思维力
    - 反应力
    - 基础数学能力
    hlevel: [2, 3, 3, 3, 3, 3, 2]
    hstyle: ""
    def:
    - 基础学习能力反映了注意力、记忆力、自控力、反应力和思维力这五个方面的综合水平，分数越高代表基础学习能力的综合发展水平越高。
    - 注意力是大脑接收和处理个体外部和内部信息的前提，只有被注意到的信息才能得到有有效的分析和处理才能用来解决问题并形成持久的记忆。注意力包含选择注意、持续注意和分配注意三个能力维度，本次施测下每个维度都有对应的施测题目，学生分数越高，代表注意力越集中。
    - 记忆力是人脑智力的集中体现，也是人脑比电脑更聪明的重要原因。个体的生存和发展需要不断掌握新的知识，记忆力能将这些 知识经验存储下来并合理运用。记忆连接着人的过去和未来，丰富着我们的精神生活并塑造着我们的性格。人脑包含复杂的记忆系统，其中联系记忆、语义记忆和短时记忆是三个重要的维度，每个维度都有对应的施测题目，学生分数越高，代表记忆力越好。
    - 自控力是人们能够根据目标和环境的要求，控制和改变自己的思想和行为，克服冲动并抵制诱惑，让自己的行为符合社会期许和长期目标的能力。自控力主要体现在控制冲动、抵制诱惑以及信息更新这三个维度，每个维度都有对应的施测题目，学生分数越高，代表自控力越强。
    - 思维力是人们接收到信息后，对信息进行归纳、概括及推理的过程。生活中，我们往往不满足于耳朵所听到的、眼睛所看到的，而是要找出事物之间的内在联系和规律，解决问题并创造出新的知识。思维力可以分为思维的灵活性、深刻性和独创性这三个维度，每个维度都有对应的施测题目，学生分数越高，代表思维力越强。
    - 反应力是对各种信息、要求和指令等做出快速反应的能力。速度是衡量反应力最重要的指标，它体现了大脑各个系统的协调、整合发展的水平，与整个神经网络的效率有密切关系。反应力可以从反应速度、言语速度和思维速度三个维度来测量。本次施测下每个维度都有对应的施测题目，学生分数越高，代表反应力越强。
    - 基础数学能力是能较为迅速、容易并透彻地掌握数学知识、技能和习惯的独特的心理特征。基础数学能力测评从数字加工、数量加工、数学计算、数学推理和空间几何这五个方面综合考察孩子的数学能力。在测验中得到的分数越高，代表基础数学能力越强。

bbp:
  customer.name: 北京市脑计划
  score.level:
    breaks: !expr qnorm(c(0, 0.3, 0.7, 0.9, 1)) * 15 + 100
    labels: !expr LETTERS[4:1]
  report.ability:
    code: [bci, Att, Mem, SC, Rsn, RT]
    name:
    - 大脑学习能力
    - 注意力
    - 记忆力
    - 自控力
    - 思维力
    - 反应力
    hlevel: [2, 3, 3, 3, 3, 3]
    hstyle: ""
    def:
    - 基础学习能力反映了注意力、记忆力、自控力、反应力和思维力这五个方面的综合水平，分数越高代表基础学习能力的综合发展水平越高。
    - 注意力是大脑接收和处理个体外部和内部信息的前提，只有被注意到的信息才能得到有有效的分析和处理才能用来解决问题并形成持久的记忆。注意力包含选择注意、持续注意和分配注意三个能力维度，本次施测下每个维度都有对应的施测题目，学生分数越高，代表注意力越集中。
    - 记忆力是人脑智力的集中体现，也是人脑比电脑更聪明的重要原因。个体的生存和发展需要不断掌握新的知识，记忆力能将这些 知识经验存储下来并合理运用。记忆连接着人的过去和未来，丰富着我们的精神生活并塑造着我们的性格。人脑包含复杂的记忆系统，其中联系记忆、语义记忆和短时记忆是三个重要的维度，每个维度都有对应的施测题目，学生分数越高，代表记忆力越好。
    - 自控力是人们能够根据目标和环境的要求，控制和改变自己的思想和行为，克服冲动并抵制诱惑，让自己的行为符合社会期许和长期目标的能力。自控力主要体现在控制冲动、抵制诱惑以及信息更新这三个维度，每个维度都有对应的施测题目，学生分数越高，代表自控力越强。
    - 思维力是人们接收到信息后，对信息进行归纳、概括及推理的过程。生活中，我们往往不满足于耳朵所听到的、眼睛所看到的，而是要找出事物之间的内在联系和规律，解决问题并创造出新的知识。思维力可以分为思维的灵活性、深刻性和独创性这三个维度，每个维度都有对应的施测题目，学生分数越高，代表思维力越强。
    - 反应力是对各种信息、要求和指令等做出快速反应的能力。速度是衡量反应力最重要的指标，它体现了大脑各个系统的协调、整合发展的水平，与整个神经网络的效率有密切关系。反应力可以从反应速度、言语速度和思维速度三个维度来测量。本次施测下每个维度都有对应的施测题目，学生分数越高，代表反应力越强。
