context:
  title:
  - 项目背景介绍
  - 测评系统介绍
  - 测评内容简介
  content:
  - 这份报告描述了贵校一年级学生在 2018 年 N 市 M 区域教育质量健康体检项目测试中的表现。本次测试基于课程标准，在关注学生应获得的知识、技能的同时，更加突出对学生基础能力的要求，特别是学生的基础学习能力，包括注意力，记忆力，自控力等基础能力，以及数学等基础学科能力。在国务院最近发布的《关于深化教育体制机制改革的意见》中，也把培养学生的认知能力作为学生能力培养的首要任务。因此，探讨有利于学生学习能力全面综合发展的科学方法和手段，成为我国当前教育改革和实践的重要任务。本次测评基于此时代背景，运用认知神经科学以及心理学知识对学生的基础学习能力和基础数学能力进行测量。
  - 本次测评使用“大脑学习能力”测评系统，该测评由北京师范大学脑与学习科学研究中心编制，整合了国际国内脑科学研究最新成果，依据脑功能分化和整合原理，以及大脑功能可塑性原理，采用计算机化认知测试的方式，全面测查与个体学习和发展密切相关的基础学习能力。同传统智力测验相比，“大脑学习能力”测评具有科学性强、实施方便、准确度高、预测效度好、可反复测试等优势，代表了当今脑力测试的新趋势。
  - 本次测评主要包括基础学习能力测评和基础数学能力测评两部分。其中，基础学习能力测评包含多种维度指标，即大脑学习能力指数（BLAI）和各个子能力维度指数(注意力指数、记忆力指数、自控力指数、反应力指数和思维力指数)。大量证据表明，个体在这些维度所代表的能力中的表现与其智力，学习能力，社会适应能力和未来发展潜力具有密切关系。同时，我们还重点考察了基础数学能力，主要测评了数字加工、数量加工、数学计算、数学推理和空间几何这五个方面的核心能力。大量证据表明，个体在这五个方面的差异与数学能力的高低具有密切关系。基础数学能力测评包含综合的基础数学能力指数和各个能力维度指数(数字加工指数、数量加工指数、数学计算指数、数学推理指数和空间几何指数)。
ability:
  name:
  - 基础学习能力
  - 注意力
  - 记忆力
  - 自控力
  - 思维力
  - 反应力
  - 基础数学能力
  - 数字加工
  - 数学推理
  - 空间几何
  - 数量加工
  - 数学计算
  description:
  - 基础学习能力反映了注意力、记忆力、自控力、反应力和思维力这五个方面的综合水平，分数越高代表基础学习能力的综合水平发展越高。
  - 注意力是大脑接收和处理个体外部和内部信息的前提,只有被注意到的信息才能得到有有效的分析和处理才能用来解决问题并形成持久的记忆。注意力包含选择注意、持续注意和分配注意三个能力维度，本次施测下每个维度都有对应的施测题目，学生分数越高，代表注意力越集中。
  - 记忆力是人脑智力的集中体现，也是人脑比电脑更聪明的重要原因。个体的生存和发展需要不断掌握新的知识，记忆力能将这些 知识经验存储下来并合理运用。记忆连接着人的过去和未来，丰富着我们的精神生活并塑造着我们的性格。人脑包含复杂的记忆系 统，其中联系记忆、语义记忆和短时记忆是三个重要的维度，每个维度都有对应的施测题目，学生分数越高，代表记忆力越好。
  - 自控力是人们能够根据目标和环境的要求，控制和改变自己的思想和行为，克服冲动并抵制诱惑，让自己的行为符合社会期许和长期目标的能力。自控力主要体现在控制冲动、抵制诱惑以及信息更新这三个维度，每个维度都有对应的施测题目，学生分数越高，代表自控力越强。
  - 思维力是人们接收到信息后，对信息进行归纳、概括及推理的过程。生活中，我们往往不满足于耳朵所听到的、眼睛所看到的，而是要找出事物之间的内在联系和规律，解决问题并创造出新的知识。思维力可以分为思维的灵活性、深刻性和独创性这三个维度，每个维度都有对应的施测题目，学生分数越高，代表思维力越强。
  - 反应力是对各种信息、要求和指令等做出快速反应的能力。速度是衡量反应力最重要的指标, 它体现了大脑各个系统的协调、整合发展的水平，与整个神经网络的效率有密切关系。反应力可以从反应速度、言语速度和思维速度三个维度来测量。本次施测下每个维度都有对应的施测题目，学生分数越高，代表反应力越强。
  - 基础数学能力是能较为迅速、容易并透彻地掌握数学知识、技能和习惯的独特的心理特征。基础数学能力测评从数字加工、数量加工、数学计算、数学推理和空间几何这五个方面综合考察孩子的数学能力。在测验中得到的分数越高，代表基础数学能力越强。
  - 数字加工是指个体加工数字符号，将其转换成数量表征，并运用其进行相应的认知加工的能力，是数学能力的基础。大脑顶内沟区域在数字加工中特别重要，其激活程度可以有效预测个体的数字加工效率。
  - 数学推理是指根据一些事实和命题，依据逻辑规则推导出一个命题的思维过程，是数学能力的核心成分。大脑的顶叶、颞叶和额叶皮层都在数学推理过程中起着重要的作用，这些区域的激活强度可以预测数学推理能力的高低。
  - 空间几何能力是指对客观事物的空间形式进行观察、分析和抽象，借助几何图形对物体的运动、变化、位置关系及数量关系进行分析和思考的一种能力，是数学形象思维的核心成分。大脑的双侧顶叶和枕叶皮层在空间几何加工中尤为重要，这些脑区的激活强度可以显著预测空间几何能力的高低。
  - 数量加工是指准确把握具体事物的数量，而且能对抽象符号所代表的数量信息进行操作和加工的能力，是数学能力的有效预测指标。大脑的顶叶和前额叶相关脑区对数量加工至关重要，这些脑区的激活强度可以有效预测数量加工能力的高低。
  - 数学计算是指根据法则快速准确进行计算，并且能理解计算的算理，会通法、懂规律，能根据题目的条件探求解题的途径，寻求简洁、合理算法的能力。大脑的顶叶顶内沟区域与数学计算能力显著相关，数学计算是逻辑思维与计算技能的结合，是数学能力中的一项核心技能。
histogram:
  description: 本校学生总体的【name】测评的得分分布见图1-3，从图中可以看出，本校学生得分呈现正态分布，分数主要集中在【】区间中，整体表现较好。本校成绩的平均数与全区总体学生平均数相比较【大中小】，差异【显著/不显著】，t=【】，p【】0.05.
  注释:
    large: 说明在【name】测评中，本校学生整体成绩显著高于本区总体学生成绩。
    small: 说明在【name】测评中，本校学生整体成绩显著低于本区总体学生成绩。
    equal: 说明在【name】测评中，本校学生整体成绩与本区总体学生成绩相近。
three-line table:
  description: 从表中我们可以看出，【1】班学生的表现最好，而【2】班学生平均数低于全校平均水平，每个班级的学生从等级优秀到不足的占比情况存在差异，应该重点关注在等级D中占比较大的班级对学生的基础能力进行有计划的训练和干预。
 注释:
【1】取值是平均数最高的班级；【2】是取值小于全校平均数的班级。

boxplot:
  description: 本校共施测5个班级，对各个班级的【name】测评分数进行了统计，结果如下图。从图中我们可以看出，【】班的总体情况与全校差异不大，【】班平均数低于总体平均数，在后期应该重点关注该班级，对能力不足的学生进行干预和有计划的训练。
appendix:
  title:
  - 本校发展建议
  content:
    title:
    - 重视基础学习能力和基础学科能力教育
    - 尊重中学生身心发展规律
    - 有针对性地推行认知能力训练
    content:
    - 学科基础能力与各个学科成绩存在着高相关，所以可以通过培养学生的学科基础能力来达到增强学科成绩的目的；此外，在重视素质教育的今天，学科基础能力的培养能让学生在纷繁复杂的信息中得到真正的能力提升，加强基础能力建设。各区县和学校应该重视学生的基础学习能力教育，定期对能力较弱的学生进行干预和训练。
    - 尊重初中生的认知能力发展规律，真正做到因材施教。研究表明，初中生抽象逻辑思维逐渐占主导地位，但具体形象成分还起作用，具有强烈的求知欲和探索精神，兴趣广泛，思想活跃，表现出较高的创造欲望。对于测评结果，我们应把握初中生思维的发展特点，目的是更好地发挥评价的导向作用，努力提高正面的积极因素，促进多元化评价的长效性。
    - 随着脑科学研究成果不断突破，对社会，学校和公众的普及和传播的不断加强，与学校教育实践的融入不断深入，脑科学与教育的结合在不远的将来会得到大大的加深。学校应该重视使用针对性的基础能力训练。基础能力训练主要是依据学生认知能力发展规律，结合个体的认知能力发展特点，制定科学性的认知能力训练任务和训练日程，针对性地提高儿童基础能力水平。例如，为了加强思维力，可以让学生每天坚持完成一些思维力训练的任务，并及时给出反馈。
